### ISSUE TITLE
“Life’s a Beach” game crash

### ISSUE THREAD

**Issue by Wanoca** [juicermv/GTA-GPS-Redux#18] opened 2023-03-30 18:51 UTC
**1.** With this mod game crashed in the mission “Life’s a Beach”, when you get closer to the beach party.

Game version: GTA SA 1.0 US
Unhandled exception at 0x006D389B in gta-sa.exe (+0x2d389b): 0xC0000005: Access violation reading location 0x00000004.
    Register dump:
        EAX: 0x04DCBB8C  EBX: 0x0C5456F8  ECX: 0x00000043  EDX: 0x3F3361B0  
        EDI: 0x4504BF8C  ESI: 0x00000000  EBP: 0x12DCC6C4  EIP: 0x006D389B  
        ESP: 0x0028F258  EFL: 0x00010206  CS: 0x00000023   SS: 0x0000002B   
        GS: 0x0000002B   FS: 0x00000053   ES: 0x0000002B   DS: 0x0000002B   
        
    Stack dump:
        0x0028F258:  0C5456F8 00000002 FFFFFFFF 00000401 00000000 00000002
        0x0028F270:  00000000 006E3305 00000401 00000002 000006E7 2276B460
        0x0028F288:  00A90670 00000001 004985DF FFFFFFFF 2276B460 00A90670
        0x0028F2A0:  0028F510 00000001 C4ECECC3 4043F951 00533522 0028F2CC
        0x0028F2B8:  0C5C4288 0028F2C0 3A194C00 BED65B38 3D966F6C 4408217F
        0x0028F2D0:  C4ECECC3 4043F951 0053426F 0028F2E4 0A872AC0 4408217F
        0x0028F2E8:  C4ECECC3 4043F951 00565046 0028F308 0028F414 00B99780
        0x0028F300:  40561315 0028F3A4 4408217F 49742400 C9742400 C9742400
        0x0028F318:  49742400 0028F414 4406FA9B C4EC2C01 4097344E 00533522
        0x0028F330:  0028F348 0C5C6A3C 0028F33C 3C221580 3D037340 3E1EDBAC
        base: 0x00090000   top: 0x0028F258   bottom: 0x00290000
        
    Backtrace (may be wrong):
        =>0x006D389B _ZN8CVehicle21AddReplacementUpgradeEii+0x6b in gta-sa.exe (+0x2d389b) (0x0028F270) 
          0x006E3305 _ZN8CVehicle17AddVehicleUpgradeEi+0x75 in gta-sa.exe (+0x2e3305) 
          

SCRLog:
```
        ...
        00007108&0: [0506] SET_CAR_MODEL_COMPONENTS 413 0 0
        00007117&0: [00A5] CREATE_CAR 413 1141307897 -991154936 1079697736 -> 7683
        00007134&0: [06E7] ADD_VEHICLE_MOD 7683 -169
```

**2.** Also, I don't know how, but this plugin fixes it (supposedly a bug from CLEO+):
"The attack with the spray can "knockback" the NPCs, instead of them doing the animation by coughing, they fly away and when they return to the ground they do the animation, some arrive to jump very high."
https://discord.com/channels/793480791509565440/796118450439061514/1015981407098646608

**3.** The game lags, the frames goes jerky when driving in a car around Los Santos.

**Comment by Wanoca** [comment] 2023-03-30 19:15
Turning off the Automatic Refresh setting in the modloader menu in the game options seems to fix this bug, but it may require further investigation.

**Comment by juicermv** [comment] 2023-04-04 05:41
I have previously encountered both issues you're describing, although from my testing they do not happen under a clean install of the game. I'm pretty sure this is caused by some incompatibility with some mod. Do you mind maybe sending over your list of mods/screenshot of your modloader directory?

**Comment by Wanoca** [comment] 2023-04-04 20:12
I have many mods. But I checked that for example Proper Player Retex + Proper Weapon Retex cause it.
I have more initiators: Original HQ Palms, ECG - VehicleTXD, Forgoten Clothes, MW Project - Lite, Proper Player Retex, Proper Weapon Retex, remake default pickups, Parked Binary IPL Fixes.
But after a successful attempt, I tried again, and it crashed again, caused by other mods. I think this crash is related to the modloader itself, but without GPS Redux or without Automatic Refresh it doesn't.

**Comment by ToMattBan** [comment] 2023-04-27 21:06
It also happens here. With the same error.
![image](https://user-images.githubusercontent.com/50156748/234991164-045401a3-9049-402e-9e99-53dad25b41d1.png)
This is my modlist, but disabling GPS Redux I didn't have the crash anymore

**Comment by juicermv** [comment] 2023-04-30 14:03
Alright thanks, I've had some of these mods with GPS Redux in the past and have encountered this same issue (it doesn't exist when some of these are disabled). I'll have to look at this later but I'll try to track down what exactly causes this.

**Comment by juicermv** [comment] 2024-01-13 02:22
Seemingly fixed as of latest build

**Closed by juicermv** 2024-01-13 02:22 UTC
Labels: bug, good first issue, known issue
